// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqoamjDqIdCCh8MY3_jcP6R1YdfvaJMGE',
    appId: '1:713556876166:web:2a9b094e86aeca6a35ea07',
    messagingSenderId: '713556876166',
    projectId: 'kiddo-shop',
    authDomain: 'kiddo-shop.firebaseapp.com',
    storageBucket: 'kiddo-shop.appspot.com',
    measurementId: 'G-JJDGTETD1G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyButLBBJWM9VOngbmOPqC_xrqzbg0Jr3vo',
    appId: '1:713556876166:android:7a4e8937364b991635ea07',
    messagingSenderId: '713556876166',
    projectId: 'kiddo-shop',
    storageBucket: 'kiddo-shop.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2B-5oHgpVufhP8OsEcokShiAFlEgsMNs',
    appId: '1:713556876166:ios:a9336ba0b6f12b6435ea07',
    messagingSenderId: '713556876166',
    projectId: 'kiddo-shop',
    storageBucket: 'kiddo-shop.appspot.com',
    iosClientId: '713556876166-pkpqgo5lk877r5ung7le83uidenhhg2r.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2B-5oHgpVufhP8OsEcokShiAFlEgsMNs',
    appId: '1:713556876166:ios:a9336ba0b6f12b6435ea07',
    messagingSenderId: '713556876166',
    projectId: 'kiddo-shop',
    storageBucket: 'kiddo-shop.appspot.com',
    iosClientId: '713556876166-pkpqgo5lk877r5ung7le83uidenhhg2r.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp',
  );
}
